# Generated by Django 2.1.2 on 2019-01-14 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_codexpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='for_whom',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='for_whom', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
