# Generated by Django 2.1.2 on 2019-01-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190114_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='punishment_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
